[package]
name = "dino-cave"
version = "0.1.0"
authors = ["Florian Merz <fmerz@mozilla.com>"]

[dependencies]
serde = "1.0.70"
serde_json = "1.0.24"
base64 = "0.9.2"
serde_derive = "1.0.70"
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
json-patch = "*"
lazy_static = "1.0"